# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templateMatcher.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonSearchImage = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSearchImage.setObjectName("ButtonSearchImage")
        self.horizontalLayout.addWidget(self.ButtonSearchImage)
        self.lineEditImage = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditImage.setObjectName("lineEditImage")
        self.horizontalLayout.addWidget(self.lineEditImage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ButtonTemplateSearch = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonTemplateSearch.setObjectName("ButtonTemplateSearch")
        self.horizontalLayout_2.addWidget(self.ButtonTemplateSearch)
        self.lineEditTemplate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTemplate.setObjectName("lineEditTemplate")
        self.horizontalLayout_2.addWidget(self.lineEditTemplate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ButtonAccept = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonAccept.setObjectName("ButtonAccept")
        self.horizontalLayout_5.addWidget(self.ButtonAccept)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 686, 350))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Imagen = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Imagen.sizePolicy().hasHeightForWidth())
        self.Imagen.setSizePolicy(sizePolicy)
        self.Imagen.setMinimumSize(QtCore.QSize(0, 0))
        self.Imagen.setText("")
        self.Imagen.setObjectName("Imagen")
        self.horizontalLayout_3.addWidget(self.Imagen)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.ImageTemplate = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageTemplate.sizePolicy().hasHeightForWidth())
        self.ImageTemplate.setSizePolicy(sizePolicy)
        self.ImageTemplate.setMinimumSize(QtCore.QSize(64, 64))
        self.ImageTemplate.setMaximumSize(QtCore.QSize(128, 128))
        self.ImageTemplate.setText("")
        self.ImageTemplate.setObjectName("ImageTemplate")
        self.horizontalLayout_4.addWidget(self.ImageTemplate)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.progressBarImage = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarImage.setProperty("value", 0)
        self.progressBarImage.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarImage.setInvertedAppearance(False)
        self.progressBarImage.setObjectName("progressBarImage")
        self.horizontalLayout_6.addWidget(self.progressBarImage)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.progressBarTemplate = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarTemplate.setProperty("value", 0)
        self.progressBarTemplate.setObjectName("progressBarTemplate")
        self.horizontalLayout_7.addWidget(self.progressBarTemplate)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ButtonSearchImage.setText(_translate("MainWindow", "Buscar Imagen"))
        self.ButtonTemplateSearch.setText(_translate("MainWindow", "Buscar Modelo"))
        self.ButtonAccept.setText(_translate("MainWindow", "Aceptar"))
        self.groupBox.setTitle(_translate("MainWindow", "Imagen"))
        self.label.setText(_translate("MainWindow", "Progreso Imagenes"))
        self.label_2.setText(_translate("MainWindow", "Progreso Template "))

